// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgnhvcjglfoypdtkevmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nbmh2Y2pnbGZveXBkdGtldm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjgxOTgsImV4cCI6MjA2MzE0NDE5OH0.537WsvU4s3CEf6eZ0c2cuhAfrSV3-hmuyfuFGEZN04U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);